// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactAppUrbanRenewal.Server.Data;

#nullable disable

namespace ReactAppUrbanRenewal.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250312130000_SeedTendersData")]
    partial class SeedTendersData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model snapshots are managed by the ApplicationDbContextModelSnapshot class
#pragma warning restore 612, 618
        }
    }
}
